import re

PRINT_TOKEN = "PRINT_TOKEN"
STRING_TOKEN = "STRING_TOKEN"
NUMBER_TOKEN = "NUMBER_TOKEN"
BOOL_TRUE_TOKEN = "BOOL_TRUE_TOKEN"
BOOL_FALSE_TOKEN = "BOOL_FALSE_TOKEN"
NEWLINE_TOKEN = "NEWLINE_TOKEN"


PRINT_REGEX = "print "
STRING_REGEX = re.compile(r'"([^"]*)"')
NUMBER_REGEX = re.compile(r'[-+]?\b\d*\.?\d+\b')
BOOL_TRUE_REGEX = "true"
BOOL_FALSE_REGEX = "false"

NEWLINE_REGEX = "\n"

PRINT_COMMAND = "PRINT_COMMAND"